### PR TITLE
Fix changePassword() documentation

### PR DESCRIPTION
**Pull request by nikwen**
The current documentation seems to be incorrect.

https://github.com/saintedlama/passport-local-mongoose/blob/0612b5b4414bc73a39c8b844a086dca5ac962c2b/index.js#L131

Correct me if I'm wrong.

### CODE REVIEW

**Comment by saintedlama** [comment]
This is not just a documentation fix as the title suggests but as the contract of the returned promise value changed a major breaking change. Naming the promise returned error `message` was an intentional decision since passport uses the argument name `message` throughout the documentation. One solution could be to provide a `message` and `error` return value for promises pointing to the same error object.

**Comment by saintedlama** [comment]
The documentation changes are awesome by the way :tada:

**Comment by nikwen** [comment]
Thank you for your quick reply! :blush: 

Is there anything you need me to change? My edit should reflect the current state of the code, right?

**Comment by saintedlama** [comment]
Thanks for the edit. The travis builds currently have some timeout issues 😭

**Comment by nikwen** [comment]
Thank you, Christoph! :)

**Pull request merged**
