### PR TITLE
Error handling: Always return instance of 'AuthenticationError'

### PR DESCRIPTION
**Pull request by fhemberger**

### CODE REVIEW

**Comment by fhemberger** [comment]
Cool, thanks!

**Comment by fhemberger** [comment]
Can you please also push a new version to npm? Should be 3.0.0, as this is a breaking change as well.

**Comment by saintedlama** [comment]
I will do a 2.1.0 version since we used the BadRequestError only so I suspect users to have checked for Error instances only. Good argument?

**Comment by fhemberger** [comment]
Hmm, all error responses containing placeholders were simple objects `{ message: 'The Error message' }`, BadRequestError was only used in 2-3 cases. Also, if people used the options for custom error messages, this will now break in their code.

**Comment by saintedlama** [comment]
Agree will do a 3.x but need to do some code clenaup/stuff before...

**Comment by fhemberger** [comment]
Cool, thanks!

**Comment by saintedlama** [comment]
Changed a lot in the past commits - wanna take a look?

**Comment by fhemberger** [comment]
Haven't tested it yet in detail, but looks good to me at first glance. :+1:

**Comment by fhemberger** [comment]
Great, the change works well for me. Ready for the new release. :+1:

**Pull request merged**
