### PR TITLE
Fix error thrown by User.changePassword() when the reason for failure is not an IncorrectPasswordError

### PR DESCRIPTION
**Pull request by nikwen**
Fixes https://github.com/saintedlama/passport-local-mongoose/issues/255

Another reason would e.g. be an AttemptTooSoonError

### CODE REVIEW

**Comment by nikwen** [comment]
Please note that this is a **breaking change**!

**Comment by nikwen** [comment]
@saintedlama Any update on this? Will it be merged?

**Comment by nikwen** [comment]
Anything? Any reply?

**Comment by saintedlama** [comment]
Took some time to take a look cause I did not maintain this repository that well for some years. Thanks for raising the PR 👍

**Comment by nikwen** [comment]
Thanks for merging!

**Pull request merged**
