### PR TITLE
Add custom callback in setPassword

### PR DESCRIPTION
**Pull request by Neozaru**
Since fields validation are usually done at save time or when calling "register", it could be good to allow password validation at the same time.
The PR simply includes a passwordValidator option with a custom callback.

### CODE REVIEW

**Comment by siboulet** [comment]
Any chances this can be merged? It's exactly what we're looking for.

**Comment by saintedlama** [comment]
Guess it does not merge anymore - see last pull request. Taking a look at this...

**Comment by siboulet** [comment]
Please see #82, really looking into getting this merged (and a version bump, too)

Thanks

**Comment by saintedlama** [comment]
Closed in favor of #82

**Pull request closed without merging**
