### PR TITLE
Update default digestAlgorithm from sha1 to sha256

### PR DESCRIPTION
**Pull request by fhemberger**
semver-major: sha1 is regarded insecure and should no longer be used

### CODE REVIEW

**Comment by saintedlama** [comment]
Thanks for the pull request! Sorry that I did not merge but I did some major changes to code formatting and stuff to get a 2.x version out so it was way easier to change these things in my editor without merging the pull request.

**Comment by fhemberger** [comment]
Thanks, I don't mind at all, as long as it got fixed. ;)
Will send another one regarding the error message handling later.

**Comment by saintedlama** [comment]
:+1: In my mental roadmap I want to use dedicated error classes to enable a programmatic differentiation of errors BUT have the same error messages used.

The reason behind this is, that for example for logging malicious logins it's required to distinguish between a user not found and a password does not match error.

**Comment by fhemberger** [comment]
Had a similar idea, I think you'll like it ;)

**Pull request closed without merging**
