### PR TITLE
add configurable algorithm

### PR DESCRIPTION
**Pull request by buehler**
Add the possibility to select the desired algorithm (SHA-1 is not secure anymore.)

-> Default will be "sha-256"

Added coding and updated readme.

Cheers ;)

### CODE REVIEW

**Comment by saintedlama** [comment]
Blows tests for node v0.10

**Comment by buehler** [comment]
well the tests already failed as I cloned the repository ;) all the changes I did were in the optional parameters, so there are no breaking changes there.

**Comment by saintedlama** [comment]
Tests failed from time to time on travis, some timeout stuff. The problem is that the hash algorithm option was introduced in node v0.12 comparing the api docs

https://nodejs.org/docs/v0.10.35/api/crypto.html#crypto_crypto_pbkdf2_password_salt_iterations_keylen_callback
https://nodejs.org/api/crypto.html#crypto_crypto_pbkdf2_password_salt_iterations_keylen_digest_callback

You'll notice that an optional digest parameter was introduced. Back in v0.10 this parameter war not accessible. Taking a look at https://travis-ci.org/saintedlama/passport-local-mongoose exactly these tests are failing. 0.12 and iojs are running fine.

**Comment by buehler** [comment]
found the issue... node v0.10 vs v0.12 broke the method signature of pbkdf2.

What do you suggest?

**Comment by buehler** [comment]
well i could add a version switch... so that the feature is only available in 0.12 and higher

any thoughts?

**Comment by saintedlama** [comment]
Could use `crypto.pbkdf2.length` to determine if a digest option is available. When you pull out the direct call of `crypto.pbkdf`into some hash function we could later on easily provide another suggested feature: multiple hashing algorithms :smile_cat:

**Comment by saintedlama** [comment]
Don't like the version switch idea. Checking argument length should be a bit cleaner cause we're not nailed to versions but detect "features" (more or less). Mocha does this, so I'm fine with argument length detection :bear:

**Comment by buehler** [comment]
never did argument length detection :) so kinda like:
if(crypto.pbkdf2.length > xx) -> use with algorithm
else -> use without
?

**Comment by saintedlama** [comment]
:+1:

**Comment by buehler** [comment]
finally :smile:

**Pull request merged**
